### ISSUE TITLE
Direct play from list of new subscriptions (or see later) play previous played video

### ISSUE THREAD

**Issue by nimbusparis** [kolsys/YouTubeTV.bundle#10]
If I select "extended video information" in the setting of the plugin and that I try to play a video from the list (without going to details of the video), it is the previous played video (event if not YouTube) that is played.

**Comment by kolsys** [comment]
What client you are use?

**Comment by nimbusparis** [comment]
Rasplex 0.5.1

**Comment by kolsys** [comment]
You need to uncheck "extended video information" for direct video playing.
