### ISSUE TITLE
How to add 'publishedAt' in video file name

### ISSUE THREAD

**Issue by j00j4nt200** [kolsys/YouTubeTV.bundle#16]
Hello,
I woud like to add 'publishedAt' (in format YYMMDD) at the begining of name of video, but don't know where to change code? 

Reason is use on xbox360 where only option is alphabetic sorting.

**Comment by kolsys** [comment]
https://github.com/kolsys/YouTubeTV.bundle/blob/master/Contents/Services/URL/YouTubeTV/ServiceCode.pys#L140

But currently no easy way to get publishedAt as timestamp. Only text version.

**Comment by j00j4nt200** [comment]
I tried few things but didn't manage to implement it.
On Serviio YT plugin it's: title : it.snippet.publishedAt + "  " + it.snippet.title, 
I don't know where/how to put 'date_text' on this plugin?

One more question please :)
I'm not sure is it Plex or plugin doing? If I understand correctly it is looking for playlists,  let say: 'Board James - Season 1' and it will automatically make sub-folder and put all content with it there, then for 'Board James - Season 2' ...
But I don't want them? All of this files is already (hopefully chronologically) in sub-folder  'video '
How can I prevent creating this sub-folders?

**Comment by kolsys** [comment]
> But I don't want them? All of this files is already (hopefully chronologically) in sub-folder 'video '
> How can I prevent creating this sub-folders?

You can disable it in Preferences.

**Comment by j00j4nt200** [comment]
Here?
![preference](https://cloud.githubusercontent.com/assets/15825225/11196327/9530a506-8cb6-11e5-8e08-383f91384e1b.jpg)

**Comment by kolsys** [comment]
Yes.

**Comment by j00j4nt200** [comment]
Didn't work.
But OK, I adapted myself, since I coudn't change program :)

Thank you for you work.
