### ISSUE TITLE
items per page

### ISSUE THREAD

**Issue by j00j4nt200** [kolsys/YouTubeTV.bundle#17]
How to change 'items per page' to 8 or some other smaller number (6, 7)
In preferences options are:16, 32, 48.

I did tried to change <items_per_page>@com.plexapp.plugins.youtube.tv.xml to 0.1 or -1 or 7 but not working.

**Comment by kolsys** [comment]
https://github.com/kolsys/YouTubeTV.bundle/blob/master/Contents/DefaultPrefs.json#L36
