### ISSUE TITLE
No ability to change Google/YouTube accounts

### ISSUE THREAD

**Issue by dougstrickland** [kolsys/YouTubeTV.bundle#19]
Once the YouTube bundle has been added, and the user has been successfully authorized through a Google account, there is no way that the user can switch to a different Google account.  

*\* I have tried removing the bundle, cycling PMS, and then reinstalling the bundle.  The script seems to write the auth somewhere outside the bundle...

**Comment by kolsys** [comment]
My channel -> Logout
