### ISSUE TITLE
Created playlist does not play all videos without manual intervention

### ISSUE THREAD

**Issue by IamSierraCharlie** [kolsys/YouTubeTV.bundle#20]
Hello,
Love this plugin and appreciate all the work that has been put into it by the contributors.
Apologies if this has been covered or I am doing something wrong.
The issue I am seeing is that when I create a playlist in YouTube, I cannot play that playlist through in its entirety.  In the bundle, I need to select the clips manually one at a time to get them to play.  Am I doing something wrong or can you tell me how I might get all the YouTube clips to play automatically one after the other.  I am on version 4.1 of the YouTube TV bundle.    My server version is Version 0.9.12.19 and can confirm that this issue exists when using Rasplex or just logging into plex server via the web or using a android phone app.
Thanks in advance for your feedback - happy new year!!
Steve

**Comment by kolsys** [comment]
You can change it in Preferences. Uncheck "Extended video info in Playlists".

**Comment by IamSierraCharlie** [comment]
This one can be marked as resolved as your suggestion has resolved my issue.
Thanks very much for your prompt response!
Greatly appreciated :-) 
Happy new year!!
