### ISSUE TITLE
New subscriptions do not appear in My Subscriptions or elsewhere

### ISSUE THREAD

**Issue by brianjcohen** [kolsys/YouTubeTV.bundle#24]
Steps to reproduce:
1. Subscribe to one or more youtube subscriptions on youtube.com.
2. Install YouTubeTV.bundle in Plex and connect to your account.
3. Observe that your existing subscriptions are visible in My Subscriptions and elsewhere in the plugin.
4. Subscribe to a new channel on youtube.com

Expected:

The new subscription should appear in the plugin, eg. in My Subscriptions.

Actual:

The new subscription does not appear. I tried restarting plexmediaserver, refreshing the page, reinstalling the plugin (although I did not try clearing the plugin's data -- I wasn't completely sure how to do that).

**Comment by brianjcohen** [comment]
Update: I came back a few hours later and the new subscription appears within the plugin now. So apparently there's some kind of delay between refreshes?

**Comment by kolsys** [comment]
The cache time is 1 hour.

**Comment by CoalaJoe** [comment]
I think someone should close this Issue
