### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by aaomidi** [kolsys/YouTubeTV.bundle#27]
When you're watching a video with this plugin, does it play it directly from youtube or does the server grab it and then stream it to the viewer? (I am asking because if its the latter it could circumvent the youtube ban in some places)

**Comment by kolsys** [comment]
It's grab video URLs from youtube and play directly from youtube.
It's fully authorized requests.

**Comment by aaomidi** [comment]
What I meant was, does youtube see the plex server IP or the user's IP?

**Comment by kolsys** [comment]
It depends on the transcoding mode.

**Comment by leelouch** [comment]
is there any way to choose resolution ? HD / 4k / etc etc  ?

**Comment by kolsys** [comment]
FullHD and 4k does not supported.

**Comment by kolsys** [comment]
FullHD and 4k not supported.
