### ISSUE TITLE
Cannot search from within Plex Media Player

### ISSUE THREAD

**Issue by NKnusperer** [kolsys/YouTubeTV.bundle#31]
There is no search bar and `Ctrl+F` just opens the internal Plex search.

**Comment by Lezardon** [comment]
You are correct. It is missing.

**Comment by mddepew** [comment]
It's a little bit non-intuitive, but it's not actually missing. If you start typing a search using the normal search bar, an option will pop up to "search youtubetv".
![capture](https://user-images.githubusercontent.com/22152922/37224519-622f8e70-2399-11e8-8552-20925bd73ab0.PNG)

**Comment by NKnusperer** [comment]
From within the Plex Web Interface this is working, but not inside the dedicated Plex Media Player app.

**Comment by HLFH** [comment]
@kolsys Reopen then?

**Comment by kolsys** [comment]
This is not plugin bug. Only plex media player developers can fix it.
