### ISSUE TITLE
Distorted sound on Samsung TV

### ISSUE THREAD

**Issue by raulmorales** [kolsys/YouTubeTV.bundle#34]
The latest plex version 1.5.3.3580 in Synology is not well-heard. On PC it sounds good but in Samsung TV it is listened distorted.

Thanks

**Comment by kolsys** [comment]
I don't think that this is a plugin problem.

**Comment by raulmorales** [comment]
I understand you're right, but what happens to someone else?

**Comment by kolsys** [comment]
Looks like transcoder changes.
