### ISSUE TITLE
Watch Later fails to load videos

### ISSUE THREAD

**Issue by bondiblueos9** [kolsys/YouTubeTV.bundle#37]
Watch later was failing to load videos and giving a channel not responding error.  There was an exception in the log for line 242 in Feed saying there was no 'contents'.  After looking at the JSON that was being retrieved, it appears that the expected format had changed.  I was able to correct this by changing line 216 from
<code>res = res['section_list']['contents'][0]</code>
to
<code>res = res['section_list']['contents'][1]['contents'][0]</code>

**Comment by kolsys** [comment]
Can you attach your version of JSON?
In my case all works ok and content processing is correct.

**Comment by RobertSmits** [comment]
I can confirm this issue and solution.

**Comment by bondiblueos9** [comment]
Immediately before line 216, I added a Log.Debug(res).  Attached is the formatted JSON from the log file.
[res.txt](https://github.com/kolsys/YouTubeTV.bundle/files/1020171/res.txt)

**Comment by bondiblueos9** [comment]
Attached is the log with my line 216 correction undone but the debug statement added so you can see the fetched json along with the exception.

[complexapppluginsyoutubetv.txt](https://github.com/kolsys/YouTubeTV.bundle/files/1020263/complexapppluginsyoutubetv.txt)

**Comment by kolsys** [comment]
Try this version
https://github.com/kolsys/YouTubeTV.bundle/tree/watchlater-fix

**Comment by bondiblueos9** [comment]
It works for me.
