### ISSUE TITLE
Cannot play any videos, keep getting this error

### ISSUE THREAD

**Issue by sschocke** [kolsys/YouTubeTV.bundle#38]
I installed the latest version of the bundle (v4.6), and restarted my Plex Server, but I cannot seem to get the videos to play

I can browse, see all my subscriptions, even get Info and see codecs, etc on all the videos, but as soon as I play one, it says it cannot be loaded. Watching from my browser works fine, and also using youtube-dl from the same machine running Plex Server also works.

Here is the output in the log file:
[YoutubeTV-error.txt](https://github.com/kolsys/YouTubeTV.bundle/files/1011551/YoutubeTV-error.txt)

**Comment by kolsys** [comment]
Did you see in your logs something like 
`Requesting 'https://www.youtube.com/yts/jsbin/player-vfluaMKo6/ru_RU/base.js'`
I need link to your version of base.js

**Comment by sschocke** [comment]
There is yes... here is the link
`Requesting 'https://www.youtube.com/yts/jsbin/player-vfl8jhACg/af_ZA/base.js'`

**Comment by kolsys** [comment]
Try this version https://github.com/kolsys/YouTubeTV.bundle/tree/jsparser-fix

**Comment by sschocke** [comment]
I have replaced the file and it seems to fix the problem.

Thanks.
