### ISSUE TITLE
Cannot play any video with Sony Bravia

### ISSUE THREAD

**Issue by gabriellluz** [kolsys/YouTubeTV.bundle#40]
Hi, I can't play any YouTube video with Sony Bravia. All my local movies and TV shows play fine except YouTube videos. Any light on this? Thx

**Comment by kolsys** [comment]
Are you using DLNA?

**Comment by gabriellluz** [comment]
Yes. But I'll close this issue since my TV is not playing ANY DLNA videos anymore. It needs a fix.
