### ISSUE TITLE
Some videos do not work

### ISSUE THREAD

**Issue by keenoar** [kolsys/YouTubeTV.bundle#42]
Thank you for this awesome plugin!

Some videos do not work:
Examples:
[LP - Lost on You](https://www.youtube.com/watch?v=hn3wJ1_1Zsg )
[Robbie Williams - Feel](https://www.youtube.com/watch?v=iy4mXZN1Zzk)

Thanks in advance :+1:

**Comment by mddepew** [comment]
This has to do with an issue in the signature decryption. I have a fix in my fork and have issued a pull request.  Kolsys will have to approve the pull before it gets merged into master. In the mean time, you can get the fix here:
https://github.com/mddepew/YouTubeTV.bundle

**Comment by kolsys** [comment]
Fixed in cd7426d66d55de0a63a36ca35018d6f7be293af6
