### ISSUE TITLE
Youtube visible in web UI, but not in Rasplex/openPHT

### ISSUE THREAD

**Issue by ToxicFrog** [kolsys/YouTubeTV.bundle#56]
Setup: I have PMS running on a headless Linux system, and Rasplex installed on two Raspberry Pi boxes.

I installed YouTubeTV.bundle in PMS and restarted the server, and it shows up in the web UI (under Online Content -> Plugins -> YouTube). I can view my subscription feed there and watch videos and whatnot and it all appears to work fine.

What doesn't seem to work is watching Youtube via OpenPHT on Rasplex. I saw that other people have reported issues with the videos showing up but not playing; I can't even get the videos to show up. Even after rebooting Rasplex, Youtube doesn't show up in the library list or the channel list.

**Comment by electricduck** [comment]
Considering OpenPHT hasn't had an official release in over a year now (and last git activity was in April), I imagine what is causing the problem is OpenPHT itself. So you're kinda out of luck.

**Comment by CollinChaffin** [comment]
Been running this on OpenPHT for Windows since the start and it still works for me OpenPHT 1.9.  Double check your config you if you are on Windows as it has to be a local issue.

**Comment by ToxicFrog** [comment]
This turned out to be 100% user error. I had enabled the "Hide 'Channels' entry in main menu" setting when I first installed rasplex, because that entry didn't have anything under it and was just wasting space, and the YT plugin shows up under Channels if installed.
