### ISSUE TITLE
Playing videos no longer works

### ISSUE THREAD

**Issue by sgtwtf** [kolsys/YouTubeTV.bundle#59]
I can view thumbnails and browse but no video plays. I checked the logs and I find  critical errors related to sandbox.py. Running on server 2016

**Comment by kolsys** [comment]
Please check v4.10

**Comment by sgtwtf** [comment]
That worked. I now have an “update available” option. I click it and it says updated to 4.10 but does not go away. New bug?

**Comment by kolsys** [comment]
Yes. Fixed.
