### ISSUE TITLE
Playback Error

### ISSUE THREAD

**Issue by courtimus** [kolsys/YouTubeTV.bundle#71]
I am able to sign in and retrieve subscriptions without issue, however when I try to play any videos I receive the error below

![Capture](https://user-images.githubusercontent.com/53061746/61490962-50944580-a96b-11e9-98e1-63e654ff8b44.PNG)

Thoughts?

**Comment by helio4k** [comment]
Having the same issue any Solution?

**Comment by kolsys** [comment]
Plex plugins are discontinued.
https://forums.plex.tv/t/plugins-i-can-access-the-options-to-all-plugins-but-no-plugin-actually-work/431518/12
