### ISSUE TITLE
Can not autorise you tube

### ISSUE THREAD

**Issue by j00j4nt200** [kolsys/YouTubeTV.bundle#73]
Sign in with Google temporarily disabled for this app
This app has not been verified yet by Google in order to use Google Sign In.

**Comment by kolsys** [comment]
I was submit the verification request but it is not fast.

**Comment by j00j4nt200** [comment]
Thank you :)

**Comment by stratgelu** [comment]
Same here

**Comment by amanalar** [comment]
Grrr, same

**Comment by Asgardsurfer** [comment]
Same here unfortunately

**Comment by nickvdm** [comment]
Same :-(

**Comment by xzcvczx** [comment]
as users, you can get around it (until the app has been verified) by going to google developers dashboard, creating a new application, add the youtube data api v3, creating a oauth page (just put whatever values in) and then create an oauth key, put the clientID and secret into YouTubeTV.bundle/Contents/Code/__init.py__ (YT_CLIENT_ID and YT_SECRET) therefore ignoring the 100 user limit until verification.

**Comment by nickvdm** [comment]
@xzcvczx this worked for me. Thanks you!
However the latest version of "youtubetv" seems to have a issue
under the "my subscriptions" tab there is a "no entries found" 
But if I go back to the main menu of "youtubetv' scroll down, select the individual channel and via video's I can watch them.... so something new to look at....

**Comment by arlion-dev** [comment]
Same and @xzcvczx doesn't work for me give me the same result.

**Comment by infinatedark** [comment]
Any idea if this issue is going to get sorted? I tried @xzcvczx idea but I just get a message saying the plugin isn't responding

**Comment by renatomarcio** [comment]
same problem.

**Comment by Lazycatsu** [comment]
Same problem. May be there is another way?

**Comment by kolsys** [comment]
Officially: The application is not approved by Google. You can use this plugin if you register own application in [Google Developer Console](https://console.developers.google.com/).
Credentials -> Create Credentials -> OAuth client ID -> TVs and Limited Input devices.
Replace variables `YT_CLIENT_ID` and `YT_SECRET` in [Contents/Code/__init__.py#L40](https://github.com/kolsys/YouTubeTV.bundle/blob/master/Contents/Code/__init__.py#L40) to your own.

```python
YT_CLIENT_ID = 'Your Client ID'
YT_SECRET = 'Your Client Secret'
```

**Comment by renatomarcio** [comment]
worked perfectly. App authorised. 
Even successfully authorising, not able to watch videos. Getting that "no items found" error....
