### ISSUE TITLE
error code: s1001 (network)

### ISSUE THREAD

**Issue by IIeTp** [kolsys/YouTubeTV.bundle#82]
Hi, I have installed the TMDBTrailer.bundle plugin version 4.2 and the current youtube plugin.
trailers are not playable. here are the logs.
[com.plexapp.agents.tmdbtrailer.log](https://github.com/kolsys/YouTubeTV.bundle/files/4915014/com.plexapp.agents.tmdbtrailer.log)

can you tell me what is the reason?

https://github.com/vmirage/TMDBTrailer.bundle/issues/4

the owner TMDBTrailer.bundle redirected me to you

**Comment by dannydvd21** [comment]
Owner of TMDBTrailer.bundle is helping me with same problem and we have it working now but only on my main account not on sub account.

**Comment by xZourSx** [comment]
Hello,

I have the same problem.
Do you have a solution ?

**Comment by xZourSx** [comment]
with log : 

Sep 05, 2020 10:52:30.132 [0x7fca12ffd700] ERROR - downloadContainer: expected MediaContainer element, found Response
Sep 05, 2020 10:52:30.132 [0x7fca12ffd700] ERROR - Unable to obtain indirect container: /:/plugins/com.plexapp.agents.tmdbtrailer/serviceFunction/url/com.plexapp.plugins.youtube.tv/YouTubeTV/PlayVideo?args=Y2VyZWFsMQoxCnR1cGxlCjAKcjAK&kwargs=.......................
Sep 05, 2020 10:52:30.132 [0x7fca12ffd700] ERROR - MDE: unable to resolve indirect container

**Comment by dannydvd21** [comment]
I downloaded a other version of the youtube plugin.
but then it only worked on mij main account not on sub accounts so i bought the plex pass 😁😜😜

**Comment by maverick56** [comment]
Same error code.
Last version of plugins.
plex in version 1.24.5.5173 on synology.

Any issu ?

**Comment by dannydvd21** [comment]
I never found a fully functional solution. 

So I think there is no way or you have to trouble shoot with the creator.

**Comment by ReenigneArcher** [comment]
I have created a working YouTube URL service that allows playback of YouTube extras.  https://github.com/LizardByte/PlexyGlass
