### ISSUE TITLE
Google blocked this app

### ISSUE THREAD

**Issue by lala187** [kolsys/YouTubeTV.bundle#85]
Hi

I am getting this message when trying to link the app to my google account: 
"This app is blocked
This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access."

Can some one help me. My less secure apps setting is on and I do not use 2 step.

**Comment by kolsys** [comment]
https://github.com/kolsys/YouTubeTV.bundle/issues/73#issuecomment-632322207
