### ISSUE TITLE
Less secure application

### ISSUE THREAD

**Issue by Ilia1** [kolsys/YouTubeTV.bundle#88]
https://support.google.com/accounts/answer/6010255
it is impossible to log into the account, even when non-secure applications are allowed in the settings. what to do?

**Comment by kolsys** [comment]
Try this https://github.com/kolsys/YouTubeTV.bundle/issues/73#issuecomment-632322207

**Comment by Ilia1** [comment]
ok, I'm logged in.
now i have an error like here https://github.com/kolsys/YouTubeTV.bundle/issues/73#issuecomment-632413218
