### ISSUE TITLE
Difficult to watch new subscription

### ISSUE THREAD

**Issue by nimbusparis** [kolsys/YouTubeTV.bundle#9]
When you go in "new video" from my subscription, I got the list of the subscriptions (wich is correct) but I cannot simply play the video, I should enter in the details of the video and click play on my remote.
Additionnaly, back to the list of video, if I click "play", this is the previous watched which is launched again.
This behaviour is the same for the list of "watch later" video.

**Comment by kolsys** [comment]
You can change it in Preferences.

**Comment by nimbusparis** [comment]
Sorry, I don't see anything in preference about it.

**Comment by kolsys** [comment]
![](http://dl2.joxi.net/drive/0011/1477/763333/150712/ecf5875cfd.jpg)
